debug: true
server:
  port: 24543
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        #healthCheckPath: ${management.contextPath}/health
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: aiNurse
        enabled: true
      enabled: true
  application:
    name: aiNurse
  datasource:
    mysql:
      url: jdbc:mysql://172.16.150.246:3306/nurse-comming-cloud?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: qqhl
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver


#  #mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
##  type-aliases-package: com.mht.springbootmybatisplus.entity #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
#  configuration:
#    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
